### ISSUE TITLE
AtCoder scraping fail when contest is running

### ISSUE THREAD

**Issue by AokabiC** [AokabiC/compro-reminder#5]
```
[ERROR] AttributeError: 'NoneType' object has no attribute 'get_text'
Traceback (most recent call last):  
File "/var/task/script.py", line 25, in lambda_handler    
  contests.extend(site.get_contestdata())  
File "/var/task/contestsite.py", line 49, in get_contestdata    
  contest_name = contest_data[1].find("a").get_text()
```

**Comment by AokabiC** [comment]
コンテスト情報取得時にコンテストが開催されていると失敗している気がする。
